# Generated by Django 3.2.16 on 2022-12-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221204_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
