# Generated by Django 3.2.16 on 2022-12-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Vente', 'Vente'), ('Echange', 'Echange'), ('Location', 'Location'), ('Location pour vacances', 'Location pour vacances')], max_length=25),
        ),
    ]
