# Generated by Django 3.2.16 on 2022-12-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_commune_wilaya'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='nom',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='wilaya',
            old_name='nom',
            new_name='nome',
        ),
    ]
