# Generated by Django 3.2.16 on 2022-12-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_commune_wilaya'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='Wilaya',
        ),
    ]
