# Generated by Django 3.2.16 on 2022-12-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_commune_wilaya'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='nome',
            new_name='name',
        ),
    ]
