# Generated by Django 3.2.16 on 2022-12-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_nome_commune_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commune',
        ),
    ]
