# Generated by Django 3.2.16 on 2022-12-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_discussion_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
