# Generated by Django 3.2.16 on 2022-12-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20221215_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postkf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=100)),
                ('surface', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('prix', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
