# Generated by Django 3.2.16 on 2023-02-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_offre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offre',
        ),
    ]
